### ISSUE TITLE
Stop the liberal dictatorship

### ISSUE THREAD

**Issue by gh67uyyghj** [jacquerie/stop-the-bullshit#6]
Stop stop-the-bullshit

**Comment by SeanKilleen** [comment]
![image](https://cloud.githubusercontent.com/assets/2148318/20471731/f4a5ad30-af81-11e6-870b-d3735d6477c8.png)

**Comment by web-connect** [comment]
Haha, in the training files, It has Trump Sexual assault's as real news, and Clinton Cash reporting as fake.

**Comment by jacquerie** [comment]
> Haha, in the training files, It has Trump Sexual assault's as real news, and Clinton Cash reporting as fake.

The labels come from Craig Silverman's dataset: https://docs.google.com/spreadsheets/d/1ysnzawW6pDGBEqbXqeYuzWa7Rx2mQUip6CXUUUk4jIk/edit#gid=1756764129.
